server:
  port: 8002

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://baozi:123456@localhost:7001/eureka
spring:
  application:
    name: buyer-mobile-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER  # swagger在2.6.x版本集成启动错误，加入该参数可以解决
  jackson:
    locale: zh
    time-zone: Asia/Shanghai
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: false

feign:
  circuitbreaker:
    enabled: true

# https://resilience4j.readme.io/docs/circuitbreaker
resilience4j:
  circuitbreaker:
    instances:
      testA:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5000
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 10
#        failureRateThreshold: 40
        slowCallDurationThreshold: 500
        slowCallRateThreshold: 30
